### ISSUE TITLE
Setting up of new web UI for Epic.Track

### ISSUE THREAD

**Issue by dinesh-aot** [bcgov/EPIC.track#157]
**Overview**
![MicrosoftTeams-image (15)](https://user-images.githubusercontent.com/101662408/235532305-a711ec54-4bf4-4b4b-98cc-8fa9d0fe7938.png)

**Comment by Connor1892** [comment]
![image](https://user-images.githubusercontent.com/126211473/235541191-4f953a45-9ad7-4cdc-93c6-670259bf6e80.png)
