### ISSUE TITLE
Warning that another User is CURRENTLY working on a form

### ISSUE THREAD

**Issue by EAO-App-Admin** [bcgov/EPIC.track#310]
**As a user I want to know whether anyone is working on a work I want to claim, so I won’t kick other people out of their work.**
[GIVEN] I logged in as a user, I went to “Tasks” tab, I saw a list of Works. I click on the work I want to work on.
[WHEN] I click on ‘Claim’ button,
[THEN] I get the message saying “User [Name Surname] is currently working on this. If you claim it now, all the work in progress might be lost. Are you sure you want to claim it?” with button options ‘Yes’ / ‘No’.

**Comment by carlygreenehill** [comment]
Note: this may be a custom component to put into the Formsflow side of the code., so it could break or need more validation time whenever formsflow has a new update available - the custom stuff could break down. 

Dinesh will look into adding this to UI Library.
