### ISSUE TITLE
Warning when navigating away from filled form

### ISSUE THREAD

**Issue by EAO-App-Admin** [bcgov/EPIC.track#311]
**As a** Superuser

**I want** to be notified if I have unsaved changes if I try to leave the page,

**so that** I can be aware that the information that I put in can be lost.

### Scenario 1: 

GIVEN I logged in as a user, I went to “Tasks” tab, I saw a list of Works. I click on the work I want to work on.
WHEN I click on another Tab - “Forms” etc.,
THEN the pop-up message appears saying “Are you sure you want to leave this page? Your work won’t be saved” with button options ‘Yes’ / ‘No’.

### Scenario 2:
 xxxxxx

### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)

**Comment by marieanik** [comment]
UX best practices: “Are you sure you want to leave this page? Your work won’t be saved” with button options ‘Leave the page’ / ‘Cancel.

**Comment by carlygreenehill** [comment]
Note from Dinesh: new feature coming in from formsflow called DRAFT, which will be a cool feature, but not replace the need for a warning modal if users haven't saved/submitted anything.
