### ISSUE TITLE
Roles Rules Matrix

### ISSUE THREAD

**Issue by carlygreenehill** [bcgov/EPIC.track#394]
Let's create a matrix, by form and function, for the ROLES in Epic Flow so that... 

Users can interact with EPIC Flow is the desired way. 

## **Acceptance Criteria**

This card is complete when there is a matrix showing different Roles and what they can and cannot do in app.

**Comment by EAO-App-Admin** [comment]
Matrix as far as I can go before next set of designs:

[https://app.zenhub.com/files/497089911/ecf065a1-7360-4949-8af8-8cf077b46975/download](https://app.zenhub.com/files/497089911/ecf065a1-7360-4949-8af8-8cf077b46975/download)
