### ISSUE TITLE
Should be able to filter Anticipated Referral based on type(Readiness Decision, Amendment ...etc)

### ISSUE THREAD

**Issue by dinesh-aot** [bcgov/EPIC.track#405]
**As a** Team Member

**I want** to be able to filter the EA referral schedule

**so that** I can create custom reports.

### Scenario 1: 

GIVEN ... (you or your condition)
WHEN ... (what you do)
THEN ... (what you see)

### Scenario 2:
 xxxxxx

### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)

**Comment by dinesh-aot** [comment]
Show the dropdown with unique tab headings to reverse filter

**Comment by Connor1892** [comment]
the PDF does not reflect the Filtered EA Schedule
