### ISSUE TITLE
Apply filters to the downloaded pdf

### ISSUE THREAD

**Issue by dinesh-aot** [bcgov/EPIC.track#448]
**Overview**
- UI will apply filters such as 
  - Global Search 
  - Column Filters
  - Column Hiding

- It should be possible to apply those filters to the downloaded pdf
- sample filters request payload
`{
    "report_date": "2023-03-15",
    "filters": {
        "exclude": [
            "ea_act"
        ],
        "filter_search": [
            {
                "project_name": [
                    "James White Park Wells"
                ]
            },
            {
                "iaac": "None"
            }
        ],
        "global_search": "aley"
    }
}`

- Do not apply this filters in the api for data. It should be only required for the pdf

**Comment by Connor1892** [comment]
working but has bugs

**Comment by Connor1892** [comment]
Throwing an error when I try to hide EA type.
The EA type is moved to the black bars automatically, so the hide EA Type toggle shouldn't care about the PDF. it only effects the webview.

**Comment by Connor1892** [comment]
removing the work team is still throwing the alignment off and removing the referral date doesn't remove the top referral date header yet. #647

**Comment by dinesh-aot** [comment]
Made the column "EA Type" non-hidable. @Connor1892 Please check
